import Head from 'next/head'
import Image from 'next/image'
import Product from '../components/Product'
import { useQuery } from 'urql'
import { PRODUCT_QUERY } from '../lib/query'
import { GalleryStyle } from '../styles/Gallary'


export default function Home() {

  // Fetch queries from strapi
  const [results] = useQuery({
    query: PRODUCT_QUERY
  })
  const { data, fetching, error } = results;

  if (fetching) {
    return <p>Loading...</p>
  }
  if (error) {
    return <p>Error: {error.message}</p>
  }
  if (!data) {
    return <p>No data</p>
  }
  const products = data.products.data;
  console.log(products);


  return (
    <div >
      <Head>
        <title>NIKE Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <GalleryStyle>
          {products.map(product => (
            <Product key={product.attributes.slug} product={product} />
          ))}
        </GalleryStyle>
      </main>

    </div>
  )
}


